### ISSUE TITLE
Sorting class in wrong <th> after reorder

### ISSUE THREAD

**Issue by DiogoDoreto** [DataTables/ColReorder#11]
Hello!

Trying out DataTables 1.10-dev with ColReorder 1.1.0-dev I've found that the sorting classes are being applied to wrong `<th>` after it has been repositioned. This doesn't occur with DataTables 1.9.4.

Example: http://jsfiddle.net/NMJsB/

Thanks!

**Comment by DataTables** [comment]
Sorry I forgot to update this. It has been fixed in the latest code: http://jsfiddle.net/NMJsB/2/ .
