### ISSUE TITLE
Provide an option to disable the click and drag reordering

### ISSUE THREAD

**Issue by DataTables** [DataTables/ColReorder#15]
This would allow just the API to do a reorder.

See: http://datatables.net/forums/discussion/19761

**Comment by rmckeel** [comment]
+1 this would be helpful! Syncing a custom controller and the built-in drag and drop is challenging and can be quirky.

**Comment by MatthewNichols** [comment]
I am up for taking this on as it forwards work I am doing at my day job. Looking at the code on lines 684 - 687 I see what looks like the wiring up of the mouse event on each TH. Is it as simple as creating a new config option (defaulting to a state that will leave the current behavior intact) and then not calling the loop that wires up the _fnMouseListener? I will give that a try. Please let me know if you can think of something non-obvious I may run into.

**Comment by DataTables** [comment]
I [recently added methods](https://github.com/DataTables/RowReorder/commit/8d588b49991786d13fda09a36373de09c81cf312) for RowReorder that allow it to be enabled and disabled. It might be worth having a look at that for the enable / disable aspect of this bug.

**Comment by MatthewNichols** [comment]
Great thanks. That will help.

Since it is your API it seems polite to ask...what do you think of the setting name "enableDrag" with a default of true to preserve the original behavior by default?

And by the way I love DataTables. Thanks for it (and the Design bookmarklet).

**Comment by DataTables** [comment]
Thanks :-)

I haven't used the name "enable*" for any of the other parameters that are boolean switches, so I wonder if "draggable" might be approriate? Or perhaps simply `enable: {boolean}` would work in this case, since the API will have a similar name to the option. And regardless of that state the API should always be able to set the ordering.

Does that make sense?

**Comment by MatthewNichols** [comment]
Yes, "draggable" sounds perfect.

**Comment by dmsmidt** [comment]
For people searching for this option here, you can prevent reordening by users with the `fixedColumnsLeft` property.

```js          
// Enable the possibility to reorder columns programmatically.
settings.colReorder = {
  // But disable this possibility for the user.
  'fixedColumnsLeft': $table.find('th').length
};
```
