### ISSUE TITLE
Data order when using ajax dataSource

### ISSUE THREAD

**Issue by FnTm** [DataTables/ColReorder#19]
I have a quite unusual use case, where I
1. Receive potential columns from the server
2. Use js to figure out the order these columns need to be in
3. Add the columns to the datatable in the original order, but pass the new order using the `aiOrder` parameter in the ColReorder settings.
4. Load the data from the server, passing along the new column order.

Now because of the column reordering happening in the front end, the data from the server has to be returned in a reordered sequence, which is all ok, and has been done. 

**The problem** is that when the table is initially loaded, the data is first put into the datatables, and only later reordered using the ColReorder plugin. But since I've already ordered the data on the server side, this initial ordering is breaking the desired column ordering.

**The solution** I came up with, was disabling the ordering server-side on the initial data loading, but that is, in my opinion, sub optimal. Could we have some sort of option that only sorts the headers of the table? Thus, the rest of the functionality could be kept as-is, and the ordering could be kept consistent.

P.S. This is as much a feature request/proposal, as sharing of knowledge.

**Comment by t2** [comment]
When you say "use objects" do you mean send back key/value pairs? I am working in Ruby and can send back a Hash instead of an Array.

**Comment by DataTables** [comment]
As [described in the manual](http://datatables.net/manual/data#Objects). It just means that you don't need to keep track of array indexes.

**Comment by t2** [comment]
Ok, I wanted to make sure. I had followed that document but had no luck using objects. No data is bound to the table.

**Comment by eudora-fabia** [comment]
> Hello,
> 
> I think that this is related to the following problem:
> 
> 1.- Load the table data from an ajax source and define that table with `ColReorder`.
> 2.- Change the order of some columns.
> 3.- Call function `table.ajax.reload()`
> 4.- You will see that column data is not positioned correctly under each column.
> 
> I have been looking for a solution and have found this old thread in DataTables forums, but it does not provide any fix: http://datatables.net/forums/discussion/3908/colreorder-fnreloadajax-and-scolumns-incorrect-cols-after-reload
> 
> If this is not directly related to this issue, I will open a new one if you prefer it.
> 
> Thanks!

Encountered this problem, seems like no fix.
