### ISSUE TITLE
Support for touchscreens

### ISSUE THREAD

**Issue by alesnav** [DataTables/ColReorder#21]
Hello,

It would be nice if ColReorder supports moving columns from touchscreens, but this could be represent a huge amount of work since there are some functions for mouse events.

I will look deeper into this tomorrow.

Thanks!

**Comment by grburgos** [comment]
Any news on the progress of this feature?

**Comment by DataTables** [comment]
Thanks for the prompt. I needed a break from other stuff. Support for touch devices committed now. I've only tested on iOS though as I don't have an Android device available at the moment.

**Comment by guy032** [comment]
when it will be available on your CDN builder?

**Comment by DataTables** [comment]
With the next release of ColReorder. I'm not yet sure when that will be.

**Comment by guy032** [comment]
thanks. I tested it on Android device using my Galaxy S7 Edge and encountered a problem.
https://s11.postimg.org/xdtbml2xv/Capture.png
the "Name" column was in the right side and after moving it to the left the .DTCR_clonedTable stays visible on the dom until I click twice on somewhere else in the page.

**Comment by guy032** [comment]
I ended up replacing this:
			.on( 'mouseup.ColReorder touchend.ColReorder', function (e) {
				that._fnMouseUp.call( that, e );
			} );

with this:
			.on( 'mouseup.ColReorder touchend.ColReorder', function (e) {
				that._fnMouseUp.call( that, e );
				setTimeout(function() {
					$(".DTCR_clonedTable").remove()
				}, 100)
			} );

**Comment by DataTables** [comment]
Interesting. If you change the `100` to `0`, does that also work?

I'm not sure why a setTimeout would be needed at all to be honest, but given its an async event anyway, I don't really see any issue with it being included.

**Comment by guy032** [comment]
I had to change the timeout from 100 to 500 to make it work all the time.

**Comment by DataTables** [comment]
That's frustrating. I'll need to see if I can grab an Android device somewhere to test it out.

**Comment by shani759** [comment]
Hi there,
I know it's a bit late to comment on this post but i came across this issue recently. I am working with **ColReorder 1.3.2** and that version does not support column swapping on devices. I have update my js file as suggested by @DataTables . After those changes column swapping working fine on android devices if i open my page in **Chrome/Mozilla**, if i use the stock browser (Samsung devices) then column swapping is not working at all so is the case of i Pads and i Phones. I have check my website on mac-book and it is working fine there. On **IOS** devices if i hold my touch then copy menu gets appeared, i disabled it but still column swapping is not working. @DataTables  you have mentioned earlier that you test this code on **IOS**. Can is ask on which devices you have checked it ?? And is there a way for me to handle this issue ?? Waiting for your response @DataTables . Thanks in advance!

P.S. @DataTables  as you have asked earlier "If you change the 100 to 0, does that also work?" I change the value to **0** and it is still working.

**Comment by DataTables** [comment]
> Can i ask on which devices you have checked it ?

iPad with iOS10 and iPhone with iOS9.(something - 3 I think).

What are you using where it doesn't work for you?

**Comment by shani759** [comment]
Thanks for such a quick response @DataTables . I have checked it on iPad 3 (9.3.3) and iPhone 6 plus (9.3.1) for those it is not working, on the contrary it is working on Samsung S3 (mobile), google nexus 7 and Samsung galaxy note 10 (tablets). 
I am using JQuery DataTable in mvc 4 application.

**Comment by DataTables** [comment]
And it is the nightly version that you are using - not the current release? Can you give me a link to the page please?

**Comment by shani759** [comment]
I have downloaded both js files (datatable.js and colReorder.js) using **Download Builder** and i have downloaded them as individual files not as a single file.

**Comment by shani759** [comment]
Previously i was using currently released js files of JQuery DataTable. After your reply i use the nightly version of js files for DataTable.js and ColReorder.js and it starts to work fine on ios devices as well as on stock browsers (Samsung devices). Thank you so much @DataTables for your timely response.

P.S. I am wondering when will these changes be available in released version ?

**Comment by DataTables** [comment]
Probably in a week or two.
