### ISSUE TITLE
Column reordering causes an Angular directive not being rendered correctly

### ISSUE THREAD

**Issue by JakubKahovec** [DataTables/ColReorder#25]
In a table's column (ver 1.10.4, colreorder 1.1.2) I have an Angular directive to render some data, through a custom renderer. It works fine, until I reorder that column, then only the raw data get displayed. I looked in the code and it is caused by calling api.rows().invalidate() on line 323. When I comment it out, the problem disappears, and the table still seems to be behaving correctly, but that's probably not the best solution. Any ideas how to fix the issue correctly ? 

Thanks 
Jakub

**Comment by aoandy** [comment]
I have the same issues and agree that commenting out this section seems to fix it.

// In 1.10 we need to invalidate row cached data for sorting, filtering etc
	//if ( v110 ) {
	//	var api = new $.fn.dataTable.Api( oSettings );
	//	api.rows().invalidate();
	//}

**Comment by smasala** [comment]
Have you built the table content inside an angular component template? This won't work. You need to access the DataTables api directly and let it build the table content for you using the `ajax/data` and `columns` config options. 

https://datatables.net/manual/data/

A "hack" would be to get angular to rebuild the table and then tell DataTables to `destroy` and `re-init` then use the DT `state` saving mechanism to restore the initial state. It's not a good idea to do this :) If you want to use Angular and DT together, then let DT do all the work and let Angular just be a container/wrapper for the table.
