### ISSUE TITLE
Is there some sort of object that holds current state of columns?

### ISSUE THREAD

**Issue by vedmack** [DataTables/ColReorder#28]
I was wonder is there is a way to get the information regarding each column original position after playing with reordering the columns using the ColReorder plugin, because I need to know for example what was the original position of some column after It was moved from place to place...

Thanks ahead,

Daniel.

**Comment by hgsadhrakiya** [comment]
Are there any events that firs when the Element Drags and drops?
I want to get the index of the column before drag & after dropped.

**Comment by DataTables** [comment]
Yes, the [`row-reorder` event](https://datatables.net/reference/event/row-reorder).
