### ISSUE TITLE
AMD module support not working?

### ISSUE THREAD

**Issue by pimlottc** [DataTables/ColReorder#29]
dataTables.colReorder.js seems to have code to support AMD by defining its dependencies:

```
// Define as an AMD module if possible
if ( typeof define === 'function' && define.amd ) {
	define( ['jquery', 'datatables'], factory );
}
```

However, this code is at the bottom of the main closure, after code that already presumes that jquery and datatable are loaded (line 109):

    $.fn.dataTableExt.oApi.fnColReorder = function ( oSettings, iFrom, iTo )

When I try to use this module with RequireJS, it throws an exception from this line before it ever gets to define the AMD module dependencies.

Shouldn't the AMD module definition be earlier in the file to ensure the dependencies are loaded before any code tries to use them?

**Comment by rockshandy** [comment]
I just noticed this bug as well, that commit does fix the issue. Is there some estimation on the next release date?

**Comment by DataTables** [comment]
About the same time as DataTables 1.10.5 I think - which should be within the next few weeks.

**Comment by rockshandy** [comment]
Cool, thanks!

**Comment by DataTables** [comment]
Sorry I just noticed that this was still open. I should have closed it - also I'm about to finally do the release!
