### ISSUE TITLE
yadcf + colreorder =  can't get focus on filter inputs

### ISSUE THREAD

**Issue by vedmack** [DataTables/ColReorder#31]
Hi, 
Wanted to get your opinion on what do you think would be the best way to solve the following problem when using yadcf plugin along with the colreorder the filter inputs can't get the focus (that they do get without colreorder) you can see this behavior in the following test case:
http://jsfiddle.net/e4685cug/  , I guess that its because of the mouse down listeners of colreorder, any suggestions on how should I solve it? and allow getting focus on my filters?

Thanks ahead, 

Daniel. 

https://github.com/vedmack/yadcf/issues/123

**Comment by DataTables** [comment]
Hi Daniel,

I'm reasonably sure it will be due to [this line](https://github.com/DataTables/ColReorder/blob/master/js/dataTables.colReorder.js#L823) in ColReorder. That is stopping the focus.

You can try removing it and see what happens...

**Comment by vedmack** [comment]
Thanks,

Solved it by adding stopPropagation to `onmousedown` (till now was calling it only `onclick` to prevent the sorting when clicking on filter)

**Comment by MrCsabaToth** [comment]
Nice, I had some trouble with this too

**Comment by vedmack** [comment]
@MrCsabaToth , I haven't added this fix to yadcf yet... But at least I know how to :)
