### ISSUE TITLE
Drag and scroll option for ColReorder

### ISSUE THREAD

**Issue by rmckeel** [DataTables/ColReorder#32]
For DataTables that extend and scroll to the right, it would be really nice to have a way to scroll automatically to the right and left when the 'scrollX' : true option is set.

I have some sample code in the answer here, but it is incomplete and I have run out of time in implementing this type of approach.  Perhaps it is something that could be incorporated into DataTables ColReorder?

http://stackoverflow.com/questions/17789163/datatables-colreorder-scroll-when-header-scrolled-close-to-boundaries/28568566#28568566

Thanks for an excellent JavaScript table library!

  Ryan

**Comment by DataTables** [comment]
Hi Ryan,

Thanks for the suggestion - completely agree. This should be something that ColReorder does. To add a little fun / complication it should perhaps also scroll the whole window for cases where the window is x-scrolling!

Probably not something I'll get a chance it implement in the near future, but certainly something I would like to add in the next major update for ColReorder.

**Comment by rmckeel** [comment]
Thanks for considering!  I am mostly finished building out an external
column reorder & filter (on/off) control.  If that's of any interest to add
to your codebase, let me know and I'll see if the client will allow
donation to open source.

Thanks - DT is a great product that has really helped us out!

  Ryan


Ryan McKeel
Practical advice for pursuing holiness in the trenches of everyday life -
whybemerelyhuman.com
<http://whybemerelyhuman.com/?utm_source=email&utm_medium=email%20signature&utm_campaign=signature>

**Comment by rsiebeling** [comment]
Hi Ryan,

I'm interested in the column reorder with the possibility to scroll.
Is there any chance it will be open sourced?

thanks in advance,
Richard

**Comment by djangosdk** [comment]
Hi @rmckeel ,
Plz share what patch did u use to fix this ..

**Comment by djangosdk** [comment]
@DataTables 
Can you please give hint how to fix this issue for time being

**Comment by DataTables** [comment]
You'd need to add this feature in the code. There is no magic "enable this feature" option since it hasn't been implement yet :-).

**Comment by djangosdk** [comment]
I am able to scroll table Horizontally with mousemove
check https://jsfiddle.net/bababalcksheep/gsf2r1v4/8/
Try moving mouse to far right.
May be something could be done to do same while reordering ..

**Comment by rmckeel** [comment]
@rsiebeling Hi Richard, if my memories serves me, I used the existing DT column reorder, but it did require some horizontal scrolling (it didn't automatically scroll once you dragged a column header to the edge of a screen).  I also made some high-level filters.  At this point, I think it'd be fairly unlikely it would be open sourced, but is there particular functionality you are looking for that I can check if the project has / could share?

Thanks!

**Comment by djangosdk** [comment]
@DataTables 

I made a commit here https://github.com/DataTables/ColReorder/compare/master...djangosdk:patch-1
Seems to work based on my solution above.

However dragging Blue line goes out of table scope if far right or far left column is dragged too quickly to opposite direction. This is problem with original plugin as well.

Any fixes,changes , improvements will be much appreciated
