### ISSUE TITLE
ColReorder possible bug

### ISSUE THREAD

**Issue by rmckeel** [DataTables/ColReorder#33]
It seems that after an fnOrder is called on colReorder, the colReorder functionality is quirky.  For example, if the order starts at [0,1,2,3,4,5] and fnOrder is called with [1,0,2,3,4,5], dragging the second header element to be first no longer works.

This is exhibited using ColReorder 1.1.2 and DataTables 1.10.2 with several other plugins and extensions installed.

If there is an easy way to do a jsbin/plunkr with a DataTables codebase (I think I've seen this before), I'd be happy to try to replicate.

Thanks!

  Ryan

**Comment by DataTables** [comment]
The behaviour of fnOrder is discussed in #27. Could you scan over that and see if that addresses your concerns?

**Comment by rmckeel** [comment]
This is resolved on my end.  The issue was that I was issuing a 'new' command instead of using the existing colReorder.  The way my code works, I don't necessarily have access to the original colReorder (this is true also if initializing colReorder from the DOM).  I think I posted a code comment, but it hasn't yet been approved on the http://www.datatables.net/extensions/colreorder/options page.

It would really help to have an example or two that had getting an existing colReorder object from a DataTable object (or even from a DOM ID) rather than just the examples of creating a new object.

So - this is not a bug.  Thanks for your response!

  Ryan
