### ISSUE TITLE
order on datatables config plus colreoder error

### ISSUE THREAD

**Issue by jouven** [DataTables/ColReorder#34]
Using:
order: [0, 'desc'], 
or orderFixed: [0, 'desc'], 
(order: [0] or orderFixed:[0] work fine) on the dataTable configuration properties plus colreoder gives an error when moving the columns.
tested on:
Palemoon 25.3.1 --> happens --> firebug details:
http://datatables.net/release-datatables/extensions/ColReorder/js/dataTables.colReorder.js line 169
error: TypeError: 0 is read-only

Iceweasel 31.6.0 --> happens --> firefox development tools (f12) details: *same details as firebug*

Internet explorer 11 --> happens --> internet explorer f12 tools:
*same place on the code as in firefox*
error: Assignment to read-only properties is not allowed in strict mode

Chromium 41.0.2272.118 --> doesn't happen 
Chrome 41.0.2272.118 --> doesn't happen 

http://jsfiddle.net/e4685cug/34/ (just reorder one column with ie11 or firefox developer tools enabled)

**Comment by DataTables** [comment]
Could you try using a 2D order array please? `order: [[0, 'desc']], `

There are some issues with using a 1D array in the initialisation options.

**Comment by jouven** [comment]
Works! Thank you for the instant response.
