### ISSUE TITLE
Wrong values in settingsDt._colReorder.s.aoTargets[#ColNum].to ?

### ISSUE THREAD

**Issue by vedmack** [DataTables/ColReorder#36]
Hi, 

Using dt: 1.10.6 , colReorder: 1.1.3

I'm might be missing something, but it looks like the colReorder holds wrong value after col reorder operation ,

Here the [test case](http://jsfiddle.net/e4685cug/43/), 

1) drag first column after the second column
2) click on the colReorder status button and watch the alert values
3) inspect the alert values , it shows 0 , 0, 1 ( i printed only the first three ) , see code
```
alert(settingsDt._colReorder.s.aoTargets[0].to + ' , ' + settingsDt._colReorder.s.aoTargets[1].to + ' , ' + settingsDt._colReorder.s.aoTargets[2].to);
```

How can I tell what is the new index of a reordered column?

Thanks ahead,

**Comment by DataTables** [comment]
The settings object ("s") is a private parameter and should never be accessed externally. Indeed, the whole settings object (`settingsDt`) in the above code shouldn't be accessed like this.

The [`column-reorder` event](https://github.com/DataTables/ColReorder/blob/master/js/dataTables.colReorder.js#L334) can be used to get information about a reordering action.

Having said that, I'm not exactly happy with the current implementation and planning a reworking of it in the next few months.

**Comment by vedmack** [comment]
Thanks, works now, what happened to the `column-reorder.dt` event?

**Comment by DataTables** [comment]
`.dt` is just the namespace. It should really be triggered with that namespace...
