### ISSUE TITLE
Column reordering with stateSave with/without serverSide

### ISSUE THREAD

**Issue by vedmack** [DataTables/ColReorder#37]
Hi,

Can it be that the `aoPreSearchCols` can sometimes (or used to be in previous version of ColReorder) to store values based on the current column order index, I mean, suppose I filtered a column N#4 and then moved it to other position to be column N#2 , then after table reload where (what index) should I look in the `aoPreSearchCols` object if I want to get that column filter value?  I used to look at the new position of the column (2) , but it looks like I should look at the original index of the column (4).
?

**Comment by DataTables** [comment]
`aoPreSearchCols` probably shouldn't ever be read directly by anything other than DataTables core (and even then, only used in one place). It is use simply to set the search values of the table and then never used again. I'm not entirely sure why I've got ColReorder modifying it...

Having said that, it is quite possible that there is some timing error occurring somewhere.

**Comment by vedmack** [comment]
So how can I tell what value was used to filter a certain column after table redraw? I need to know that because I want to show that value in filter input (right now I use the `aoPreSearchCols`)

**Comment by DataTables** [comment]
My mistake - you are correct. I was thinking of the initialisation option...

[`column().search()`](http://datatables.net/reference/api/column().search()) is the public API to get search information, but it should be possible to use `aoPreSearchCols` still.

It sounds like there is an issue with the order of execution - the columns being reordered shortly after you read the data for example. I'll need to experiment a bit (but a bit of a backlog atm, so it will be at least next week before I can I'm afraid).
