### ISSUE TITLE
Unable to create webjar for v1.1.3 at www.webjars.org/bower

### ISSUE THREAD

**Issue by ttran17** [DataTables/ColReorder#40]
Hi, I tried to use the on-demand webjar creator at http://www.webjars.org/bower for the latest release (1.1.3) but it complains about a missing license file (which is clearly in the master branch).

Perhaps the on-demand tool is case-sensitive when it looks for the license file? Anyhow, I don't know the exact issue but if you have time could you deploy the webjar for 1.1.3 at www.webjars.org?

Thanks very much.

**Comment by DataTables** [comment]
I've just [added the license to the bower file](https://github.com/DataTables/ColReorder/commit/fc8bd578c54) which it looks like webjars needs. However, it would also appear that this information needs to be present on a tagged version, and I'm currently in the middle of making a large set of changes to the DataTables extensions. As such, I'm not ready to release a new version just yet.

When v1.2.0 is available this will start working again.

Thanks for flagging it up.

**Comment by DataTables** [comment]
It looks like someone has already built ColReorder 1.2.0 with webjars.org. The package name to search for is `datatables.net-colreorder`. See also the [DataTables bower instructions](http://datatables.net/download/bower).
