### ISSUE TITLE
Row invalidation on reordering reads from the DOM

### ISSUE THREAD

**Issue by DataTables** [DataTables/ColReorder#42]
Reposting from the issue posted by @jamezamm at [DataTables/DataTables #637](https://github.com/DataTables/DataTables/issues/637).

Test Case: http://live.datatables.net/xijeqige/2/edit

In the example above, I'm adding a text box to the cell through the createdCell callback and then checking if the row data (array or object) has changed.

Steps to reproduce the issue:

Change the value of any text box.
In the console, one can see that the row data still has the value and not the text box html.
Reorder any column by dragging the column into a different position.
Change the value of any text box.
In the console, one can see that the row data now has the text box html and not the value.
Please note that this issue appears only when reordering a column.

**Comment by DataTables** [comment]
So the issue here is that when the row is reordered it will invalidate the data contained in the row, causing DataTables to re-read the data from the source into its various caches (filtering, sorting, etc).

That invalidation, since you are using a DOM sourced table, will cause DataTables to read from the DOM cell, which you have overwritten. Thus DataTables uses that new data.

Ajax or JS sourced data shouldn't have this issue since the invalidation causes a read from the data source, not the DOM.

I'm not sure how the setup in your example can be made to work with a DOM sourced table. I'll leave this issue open for a bit so I can have a chance to think further on it, but the workaround for now is to use Ajax or JS sourced data.

**Comment by jamezamm** [comment]
Thanks for the swift reply. 

I can confirm that this isn't the case when using ajax sourced data.

But there is a different problem, which is show in another test case: http://live.datatables.net/yofadage/1/edit

Reorder the name column in a new position to see the issue. 

As you can see, the text box is being lost as it is reading from it's data source. Why can't it just use the cached node, instead of reading from the data source?

**Comment by DataTables** [comment]
It probably should just leave the node along, and invalidate only the cached data. That perhaps is the best approach here. It will require a modification in DataTables to make that happen since it doesn't give that ability at the moment. It will probably be a bit of time before I can look at this in depth I'm afraid, due to the current back log of support requrests. But i'll post back when I have been able to do so.

**Comment by jamezamm** [comment]
Why does it need to invalidate the cached data, just for reordering? And I really don't think this has something to do with the core, most probably is the function that is reordering the columns inside the ColReorder. 

Thanks again.

**Comment by DataTables** [comment]
The invalidation has to happen because DataTables stores the cached information based on column index. Without the invalidation if you reordered column 2 to be column 1, the search cache for what is now column 1 would refer to column 2!

**Comment by jamezamm** [comment]
Good Point. Thanks.

**Comment by DataTables** [comment]
I think the key here is this comment from myself:

> That invalidation, since you are using a DOM sourced table, will cause DataTables to read from the DOM cell, which you have overwritten. Thus DataTables uses that new data.

That is the correct thing to do in the majority of cases. If you invalidate a row it should read the original data source. As such, I think this is an edge case for it wanting to not re-read the original data (although it could also improve performance) so for the moment I'm going to close this as we have a workaround to use Javascript or Ajax sourced data.
