### ISSUE TITLE
Sorting bug after reordening

### ISSUE THREAD

**Issue by 1Jesper1** [DataTables/ColReorder#44]
Is this bug already fixed?

https://datatables.net/forums/discussion/22159/datatables-1-10-1-and-colreorder-sort-indication-problem

When I try the example on the documentation site, I'm still able to reproduce the problem.
Demo:
http://datatables.net/extensions/colreorder/examples/initialisation/simple.html

**Comment by DataTables** [comment]
Yes it has been. Unfortunately, there is a different bug in DataTables 1.10.8 which you can see if you open the console in your browser on the page you linked to. This has been resolved in the DataTables 1.10.9-dev nightly.
