### ISSUE TITLE
Integration with Colvis

### ISSUE THREAD

**Issue by MuellerMatthew** [DataTables/ColReorder#46]
The following example of integration with Colvis does not work: 
https://www.datatables.net/extensions/colreorder/examples/integration/colvis.html , it keeps generating errors in Chrome with `uncaught TypeError: b.getAttribute is not a function` when you attempt to drag a column, and the columns bounce back to their original positions.

**Comment by DataTables** [comment]
This is actually an error in DataTables rather than ColReorder or the Buttons column visibility module. It was fixed by [this commit](https://github.com/DataTables/DataTablesSrc/commit/7b14969092e240) and will be released as part of 1.10.9.
