### ISSUE TITLE
Javascript Error thrown when re-ordering

### ISSUE THREAD

**Issue by finkedave** [DataTables/ColReorder#47]
I get a jquery error of b.getAttribute is not a function  anytime I try to re-order the columns. Via drag and drop and via api order()

I get the same error even on the example page https://www.datatables.net/extensions/colreorder/examples/initialisation/simple.html.

Happens in chrome and firefox mac versions if that matters. Still seems like the re-ordering for the most part works but seeing that error makes me think something is being done right.

thanks

**Comment by DataTables** [comment]
Hi - this was covered by #44. DataTables 1.10.9 will be released soon with the fix.
