### ISSUE TITLE
Does not trigger createdCell-Callback

### ISSUE THREAD

**Issue by heannig** [DataTables/ColReorder#49]
The plugin should trigger the createdCell-Callback on reordering a cell. 

In my case, I structured my cell data like 
```{ 'title' : 'cell title',
 'content' : 'cell content'
} ```
and I use the createdCell-Callback to let the cell look like ```<td title="cell title">cell content</td>```

If I use the ColReorder-Plugin the callback is not triggered and the cell content is like
```<td>{ 'title' : 'cell title', 'content' : 'cell content'}</td>```

**Comment by DataTables** [comment]
I don't believe it should trigger `createdCell`, since it hasn't created the cell - that callback should only ever be called once in the life time of the cell.

However, DataTables should provide an `updatedCell` event. That is something I will be adding to the next major version of DataTables.

**Comment by heannig** [comment]
Great! Looking forward

**Comment by DataTables** [comment]
Going to close this one now - I should have done before. This is something for DataTables core.

**Comment by paulgerman94** [comment]
Any updates on this?

I'm having the same issue.

Also, I don't understand why all cells have to be redrawn when moving the columns.
Whatever column I move, the data in all the cells in which I use createdCell goes back to default.

**Comment by DataTables** [comment]
I've not been able to implement the required events into DataTables core yet. That will come in the next major version.

> Also, I don't understand why all cells have to be redrawn when moving the columns.

It does a `row().invalidate()` on the rows, which results in the data source being reread. That is required because the filtering and sort cache for each row is stored in column indexed arrays. The upshot is that it will also redraw the contents of the cell.

**Comment by smasala** [comment]
@DataTables what's the current best practice for this? I have a cell which renders some interactive dom elements in the `createdCell` callback. After a reorder the cell prints a string of the object `[object Object]`. Any ideas what would be the best thing to do after a `column-reorder` event to recreate my dom elements? Thanks in advance

**Comment by DataTables** [comment]
Depending upon exactly what your DOM elements are doing it might be appropriate to simply have `columns.render` return an HTML string. If you have any event listeners for those cells, then delegated event listeners could be used. That's currently the best (only sane) way to handle dynamically built HTML in cells.

**Comment by smasala** [comment]
Is `render` called after reorder too? If I remember right I chose createdCell because it was called less often than the `createdCell` callback was.

I decided to delegate to the cell DOM creation to a separate function and call the same function in the reorder callback.

```js
var scope = this;
createdCell: function(cellElement, ...) {
    var $cell = $(cellElement);
    $cell.addClass("some-class-identifier");
    createDomElements($cell);
}
...
var scope = this;
myDatatableInstanceVariable.on("column-reorder", function() {
    $(myDatatableInstanceVariable.table().node()).find(".some-class-identifier").each(function() {
        scope.createDomElements($(this));
    });
});
...
createDomElements = function($cell) {
   // do something
}
```

**Comment by DataTables** [comment]
It should be yes. [`rows().invalidate()` is called](https://github.com/DataTables/ColReorder/blob/master/js/dataTables.colReorder.js#L334) which will rerender the cell.

**Comment by camila-rodrigues** [comment]
Any updates about it?
I'm having the same problem, and I don't know what the better solution.

**Comment by jrgprzm** [comment]
I know this issue has been oppened for a while now. I've fixed the issue by changing the invalidate calls from `.invalidate()` to `invalidate('dom')`. That preserves the events and the html generated by createCell.

**Comment by anu91ab** [comment]
Hi,

Is there any updates to triggering createdCell callback function as well when rows().invalidate() is called ? Would have been really helpful il updating my dynamically rendered component.

**Comment by AllanJard** [comment]
No sorry. The cell is not recreated when invalidate is called, so `createdCell` is not called. Possibly the `draw` event might be best?

**Comment by anu91ab** [comment]
@AllanJard , Thanks for the response. 

But, since the <td> is recreated isn't it ideal to consider there has been a cell recreation. Otherwise, is it possible to introduce another render callback specific to cell (instead of 'render'); to favour injecting custom components into tdElement directly.

**Comment by AllanJard** [comment]
Yup - there is a problem there no question! The cell isn't recreated, but rather re-used. If it were actually created, then `createdCell` would be called again. I agree that there needs to be something more explicit here for DataTables to handle live DOM elements being inserted into the cells. It is a limitation at the moment I'm afraid.

**Comment by anu91ab** [comment]
Okay,

Can you help me how I can get a tdElement within 'render' based on a column configuration object property (say title === 'Name'). Don't we just get the entire dataObject and the rowIndex within the render. How can i dynamically identify the column within render :(

**Comment by AllanJard** [comment]
The `render` function has a fourth parameter passed to it which is an object that contains `row` and `col` properties to identify the row and column indexes.

**Comment by anu91ab** [comment]
Hi @AllanJard , 

Can you help me out --

I need to clear out the dynamic components inserted in 'render' callback fn. How can i know that render is about to be triggered, so that I can unmount/destroy/clear all of them , to re-initialize in the updated cell-index/element

**Comment by AllanJard** [comment]
I suspect that you would need to actually use the `drawCallback` function (or `draw` event) to do this with the rendered table cells at the moment. The renderer just doesn't have a reference to the node - at least not a public one! If you really wanted to you could use:

```js
render: function (data, type, row, meta) {
  if (type === 'display') {
    let cell = meta.settings.aoData[ meta.row ].anCells[ meta.col ];

    // ...
  }
}
```

But keep in mind that it is possible that the cell isn't yet created when the rendering function is called. I would not recommend using this method since it uses DataTables internal properties which can, will and do change.

**Comment by anu91ab** [comment]
Hi @AllanJard , 

Pardon me on getting back this late. But, I have a problem. 

DrawCallback isn't fired in case of reorder, after all of 'render' is executed.

Is there any other callback fn that is fired after a render? 

If not, it makes it impossible to identify that has a render cycle has been run, and updates components need to be overwritten over the cells.
Please see if you can help me out!

**Comment by AllanJard** [comment]
[The `row-reordered` event](https://datatables.net/reference/event/row-reordered) will be triggered once the row reordering has been done.

**Comment by anu91ab** [comment]
@AllanJard , In coordinance to this issue; I tried https://github.com/anu91ab/DataTablesSrc/commit/0a5ee8c0dbcf4ea71d3a24d1c12ed2f3d0441273

I was hoping to trigger the same callback function on createdRow and render. But, it seems render always expects a string; as doing like this prints undefined in the cells. Can you help me figure any way out!
