### ISSUE TITLE
cell select doesn't work on reorder

### ISSUE THREAD

**Issue by MadsHL** [DataTables/ColReorder#51]
The cell selector doesn't find the right cell after reorder, except when you adding a new line.

The below example finds the cell for the original position of $td.

$td.bind("click", function (e) {
   that.table().cell(this);
});

**Comment by DataTables** [comment]
Thanks for flagging this up. I've put together a simple test case here: http://live.datatables.net/lafatobu/1/edit .

I'll reply back once I've had a chance to look into this in more detail, but due to a backlog of other support requests that might take a bit of time.

**Comment by DataTables** [comment]
Note to self (wrapping up for the day atm) - this is due to the cached cell index that DataTables adds to the nodes in the table. ColReorder will either need to update them, or the DataTables invalidate method will need to do so.
