### ISSUE TITLE
Columns GET value order does not match UI when using serverSide Ajax option

### ISSUE THREAD

**Issue by dustinalan** [DataTables/ColReorder#52]
Currently, there is no data sent to the server side indicating what order the columns are in when using the colReorder extension and serverSide.

The ajax URL columns parameter array does not match the order of columns in the reordered DataTable. The URL array always shows the original order of fields when .DataTable() was initialized.

If we could manipulate the code to change this column order, then creating a CSV file that matches the order of DataTable fields that the user sees could be possible. 

I'm using the following options on my DataTable.

    $(document).ready(function () {
        var ordersTable = $('#ordersTable').DataTable( {
            "pageLength": 50,
            "scrollX": true,
            "stateSave": true,
            "colReorder": true,
            "processing": true,
            "serverSide": true,
            "searchDelay": 800,
            "ajax": "/search/",
            "columns": [{"data": "orderUpdatedTime"},
				{"data": "domainName"},
				{"data": "visitName"},
				{"data": "environment"},
				{"data": "status"},
				{"data": "submitResponse"},
				{"data": "domainId"},
				{"data": "ipAddress"},
				{"data": "subTotal"},
				{"data": "shippingTotal"},
				{"data": "taxTotal"},
				{"data": "grandTotal"},
				{"data": "billingCity"},
				{"data": "billingState"},
				{"data": "billingPostalCode"},
				{"data": "shippingCity"},
				{"data": "shippingState"},
				{"data": "shippingPostalCode"}]
        });

        // redirects the user to a CSV export tool, but the CSV will always have the same order of columns
        $('#downloadCsv').click(function(){
            window.open('/csv-export/?' + $.param(ordersTable.ajax.params()));
        });
    });

When I decode the _GET URL to process the CSV file it's always in this order:

    array (
      'draw' => '1',
      'columns' => 
      array (
        0 => 
        array (
          'data' => 'orderUpdatedTime',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        1 => 
        array (
          'data' => 'domainName',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        2 => 
        array (
          'data' => 'visitName',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        3 => 
        array (
          'data' => 'environment',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        4 => 
        array (
          'data' => 'status',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        5 => 
        array (
          'data' => 'submitResponse',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        6 => 
        array (
          'data' => 'domainId',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        7 => 
        array (
          'data' => 'ipAddress',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        8 => 
        array (
          'data' => 'subTotal',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        9 => 
        array (
          'data' => 'shippingTotal',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        10 => 
        array (
          'data' => 'taxTotal',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        11 => 
        array (
          'data' => 'grandTotal',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        12 => 
        array (
          'data' => 'billingCity',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        13 => 
        array (
          'data' => 'billingState',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        14 => 
        array (
          'data' => 'billingPostalCode',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        15 => 
        array (
          'data' => 'shippingCity',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        16 => 
        array (
          'data' => 'shippingState',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
        17 => 
        array (
          'data' => 'shippingPostalCode',
          'name' => '',
          'searchable' => 'true',
          'orderable' => 'true',
          'search' => 
          array (
            'value' => '',
            'regex' => 'false',
          ),
        ),
      ),
      'order' => 
      array (
        0 => 
        array (
          'column' => '0',
          'dir' => 'asc',
        ),
      ),
      'start' => '0',
      'length' => '50',
      'search' => 
      array (
        'value' => 'searchInputValue',
        'regex' => 'false',
      ),
      '_' => '1454118838762',
    )

No matter what order I put the fields in, I always get a URL like so:

https://domain-name.com/search/?draw=1&columns%5B0%5D%5Bdata%5D=orderUpdatedTime&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=domainName&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=visitName&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=environment&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=status&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=ipAddress&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=domainId&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=subTotal&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=shippingTotal&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=taxTotal&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=grandTotal&columns%5B10%5D%5Bname%5D=&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=billingCity&columns%5B11%5D%5Bname%5D=&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B12%5D%5Bdata%5D=billingState&columns%5B12%5D%5Bname%5D=&columns%5B12%5D%5Bsearchable%5D=true&columns%5B12%5D%5Borderable%5D=true&columns%5B12%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B12%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B13%5D%5Bdata%5D=billingPostalCode&columns%5B13%5D%5Bname%5D=&columns%5B13%5D%5Bsearchable%5D=true&columns%5B13%5D%5Borderable%5D=true&columns%5B13%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B13%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B14%5D%5Bdata%5D=shippingCity&columns%5B14%5D%5Bname%5D=&columns%5B14%5D%5Bsearchable%5D=true&columns%5B14%5D%5Borderable%5D=true&columns%5B14%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B14%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B15%5D%5Bdata%5D=shippingState&columns%5B15%5D%5Bname%5D=&columns%5B15%5D%5Bsearchable%5D=true&columns%5B15%5D%5Borderable%5D=true&columns%5B15%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B15%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B16%5D%5Bdata%5D=shippingPostalCode&columns%5B16%5D%5Bname%5D=&columns%5B16%5D%5Bsearchable%5D=true&columns%5B16%5D%5Borderable%5D=true&columns%5B16%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B16%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B17%5D%5Bdata%5D=submitResponse&columns%5B17%5D%5Bname%5D=&columns%5B17%5D%5Bsearchable%5D=true&columns%5B17%5D%5Borderable%5D=true&columns%5B17%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B17%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=50&search%5Bvalue%5D=searchInputValue&search%5Bregex%5D=false&_=1454117534217

**Comment by DataTables** [comment]
DataTables should be sending the `columns[].data` property to indicate the column order ([described in the manual](http://datatables.net/manual/server-side)).

That property looks to be present in the above URL.

Could you link to a page showing the issue so I can debug it please.

**Comment by dustinalan** [comment]
Right, but the order is always the same.

Let me see if I can get this up somewhere it can be tested. It's currently behind a VPN.

**Comment by DataTables** [comment]
The above fix should address this - thanks for letting me know about it!
