### ISSUE TITLE
Error when combined with a hidden column

### ISSUE THREAD

**Issue by raphaelgera** [DataTables/ColReorder#58]
Example in [JSBin](http://jsbin.com/fihale/edit?html,js,output) 

Scenario: Using ColReorder together with [Column Visible](https://datatables.net/reference/option/columns.visible) and setting the first column to hidden

Result: Drag N Drop is out of sync, the blue line is not positioned correctly and the column being dragged does not update in its place but further to the right.

Hypothesis: Code is calculating the hidden column

**Comment by DataTables** [comment]
Already been fixed by this commit: https://github.com/DataTables/ColReorder/commit/23836070a8c092804f863a66e2d527abf48bc06d .

http://jsbin.com/dilavuduqo/1/edit?html,js,output :-)

**Comment by raphaelgera** [comment]
Amazing!
