### ISSUE TITLE
RTL functions backwards

### ISSUE THREAD

**Issue by legshooter** [DataTables/ColReorder#59]
In RTL:
Moving the first column to the second, puts it second from last.
Moving the first column to the third puts it third from last.
etc.

**Comment by DataTables** [comment]
Thanks for letting me know about this. Not sure when I will get a chance to fix it, but I will post back here when done.

**Comment by m-amgad** [comment]
Dears,
Any updates about this issue?
Thanks,

**Comment by DataTables** [comment]
No Sorry. As I said above, I'll post back when done. Pull requests welcome.
