### ISSUE TITLE
Problem when calling the callback function in stateLoadCallback

### ISSUE THREAD

**Issue by tokland** [DataTables/ColReorder#62]
[jQuery compat 1.12.4, DataTables 1.10.13, ColReorder 1.3.2]

This problem was originally reported at the forum by stoffel on December 2016: https://datatables.net/forums/discussion/39351/column-reordering-colreorder-not-working-when-calling-the-callback-function-in-stateloadcallback?

As he states, the state loading works fine for sync `stateLoadCallback` but not for async `stateLoadCallback`.

**Comment by DataTables** [comment]
Have you try the [nightly version](//datatables.net/download/nightly)?

**Comment by tokland** [comment]
Weird, https://nightly.datatables.net/colreorder/js/dataTables.colReorder.min.js appears empty. Just me?

**Comment by DataTables** [comment]
No - looks like a bug with the compressor. I'll look into it. The non-min version is okay.

It would also be the nightly of DataTables that you need to fix this issue I think.

**Comment by tokland** [comment]
Ok, using non minified version. Using Nightly DT + nightly ColOrder, not working for me.

**Comment by DataTables** [comment]
Thanks. If you could post a link to a test case showing the issue, I'll take a look later in the week.

**Comment by tokland** [comment]
Sure: http://download.zaudera.com/public/datatables-colreorder-async.html

Check the part:

```
          // Return - It works:
          //return JSON.parse(data);
          
          // Callback - This does not work:
          callback(data);
```

**Comment by DataTables** [comment]
I think it was [fixed in this commit](https://github.com/DataTables/DataTablesSrc/commit/5de12df3799542e2955ce47eda9b654b913bc36d). The [nightly version](https://nightly.datatables.net/js/jquery.dataTables.min.js) does now carry that fix (it didn't before). Might you be able to try it again now?

**Comment by tokland** [comment]
Thx, Allan, it does work now.
