### ISSUE TITLE
ColReorder 2 columns with different data type

### ISSUE THREAD

**Issue by alex-michaud** [DataTables/ColReorder#63]
I have a table with a few columns.
Column A at position 3 is of type "string".
Column B at position 4 is of type "datetime".

If I reorder those 2 columns, the columns header and data seem to be ok but there is a problem with the display.

The column B is now at position 3, but instead of seeing the properly formated date and time, I have an  unformatted value that look like this : "2014-08-18T16:36:00+08:00"

The column A is now at position 4, but instead of seeing the string I have the error message : "Invalid date".

Reordering the columns isn't supposed to automatically move the data type?

I haven't found a workaround yet. Any suggestion?

**Comment by DataTables** [comment]
Can you link to a page showing the issue please?

Also, in future, could you post support questions in the [forums](//datatables.net/forums) as requested in the new issue template text please? The reasoning for that is to keep the forums as a searchable corpus of knowledge for DataTables.

**Comment by alex-michaud** [comment]
It's an intranet app. I could try to recreate the problem on a publicly accessible website.
I just posted the question on the forum. 
I think it belong here as well. I have been using datatables for the past few months on this intranet app and it have been great so far. In fact, it's the first time I encounter a problem with it that I'm not able to solve easily.

**Comment by DataTables** [comment]
Thanks for posting the question in the forum ([link](https://www.datatables.net/forums/discussion/41198/colreorder-2-columns-with-different-data-type#latest)).

Let's continue the discussion there if that's okay.
