### ISSUE TITLE
Sorting function doesn't work with ColReorder

### ISSUE THREAD

**Issue by marcvidalim** [DataTables/ColReorder#66]
Hello,

I've asked in datatables support forum but I didn't get an answer, in order to priorize it I'm opening this new issue.

https://datatables.net/forums/discussion/42661/sorting-function-doesnt-work-with-colreorder

I hope you can help me with it and I apologize I'm not proceding as wished.

Thank you!

**Comment by DataTables** [comment]
I've added a reply now.

If you would like to prioritise your support questions, there are [support packages available](https://datatables.net/support/).
