### ISSUE TITLE
Cannot read property '_ColReorder_iOrigCol' of undefined

### ISSUE THREAD

**Issue by fuscage** [DataTables/ColReorder#70]
Hello, I am using DataTables 1.10.15 and ColReorder 1.3.3 
And receiving the following error "Cannot read property '_ColReorder_iOrigCol' of undefined", this only happens when State Saving is enabled. 
My error when I active the stateSave  and the ColReorder :

TypeError: Cannot read property '_ColReorder_iOrigCol' of undefined
    at i._fnStateSave (dataTables.colReorder.min.js:17)
    at jQuery.fn.init.<anonymous> (dataTables.colReorder.min.js:14)
    at jquery.dataTables.min.js:75
    at Function.map (jquery.js:484)
    at s (jquery.dataTables.min.js:75)
    at jQuery.fn.init.za (jquery.dataTables.min.js:71)
    at jquery.dataTables.min.js:75
    at Function.map (jquery.js:484)
    at s (jquery.dataTables.min.js:75)
    at O (jquery.dataTables.min.js:30)
fire @ jquery.js:3232
fireWith @ jquery.js:3362
ready @ jquery.js:3582
completed @ jquery.js:3617

I have see this article : https://datatables.net/forums/discussion/25120/cannot-read-property-colreorder-iorigcol-of-undefined
But, with the order: [[1, 'asc']], I have also the error

Thanks for your help

**Comment by DataTables** [comment]
Can you link to a page showing the issue please.

**Comment by yanikore** [comment]
This error happens a lot when stateSave is enabled and data has been stored in localStorage. Try clearing it.
