### ISSUE TITLE
Sorting changes on Reordering columns when Scrolling is enabled

### ISSUE THREAD

**Issue by Ram-Sys** [DataTables/ColReorder#74]
This problem can be reproduced with an example from ColReorder documentation:

https://datatables.net/extensions/colreorder/examples/initialisation/scrolling.html

When you drag a th-element to another position in the th-row and drop it there, the sorting gets triggered (in almost every case) which is not expected behavior.

When you drop the th-element above or below the th-row, it works as expected like in the basic example without scrolling. The sorting stays the same:

https://datatables.net/extensions/colreorder/examples/initialisation/simple.html

I have tested this with enabling scrollX and/or scrollY. In every case this behavior appears.

**Comment by DataTables** [comment]
I'm not seeing that behaviour I'm afraid. What browser are you using?

**Comment by Ram-Sys** [comment]
Firefox 59.0.2 (With Chrome 65.0 I cannot see this behavior too)

**Comment by Ram-Sys** [comment]
You can avoid this issue with disabling the realtime-updating of colreorder (https://datatables.net/extensions/colreorder/examples/initialisation/realtime.html).
