### ISSUE TITLE
ColReorder.aoInstances[f].s.dt.oInstance==g returns false in some cases

### ISSUE THREAD

**Issue by gilluminate** [DataTables/ColReorder#8]
if you pass oTable immediately after creating it on the document ready, then 
    ColReorder.aoInstances[0].s.dt.oInstance==oTable

will return true.

If you later set (in your app.js somewhere after the initial table has been rendered)

    oTable = $('#example').dataTable();j

Then the above will return false.

Since ColReorder uses this line for the fnReset() method, it fails in that case and column order cannot be reset.

I hope this makes sense.

![Screen Shot 2013-02-28 at 4 12 13 PM](https://f.cloud.github.com/assets/103820/207761/56fe76f4-81fc-11e2-9833-e806e6318dc9.png)

**Comment by DataTables** [comment]
Sorry I didn't reply to this issue at the time - 2 years must be some kind of record (not one I am proud of!)! The `aoInstances` array has been removed in the newer versions of ColReorder so this should no longer be an issue.
