### ISSUE TITLE
Reordering columns in Firefox resorts the column

### ISSUE THREAD

**Issue by njmullen** [DataTables/ColReorder#81]
When using colreorder to reorder columns, the column being reordered will resort each time it is moved. This issue is only present in Firefox, not Chrome. 

Is this a known issue or has anyone come across this before?

**Comment by DataTables** [comment]
I wasn't aware of that - thanks for letting me know. I'm not sure when I'll get to this issue I'm afraid. I'll certainly look at it before the next ColReorder release though.

**Comment by colin0117** [comment]
Hi @njmullen ,

I just tried that here - http://live.datatables.net/mofumoda/1/edit - and I'm not seeing any additional sorts. Could you say how to reproduce on that test case, please.

Cheers,

Colin

**Comment by AllanJard** [comment]
I've rewritten ColReorder and with v2 I'm no longer seeing this effect in Firefox.

**Comment by rttc-mm** [comment]
This is still an issue with ColReorder 2.0.4 in the current Firefox version. 
A call of event.preventDefault() in mousedown and mouseup handler solves the problem.

**Comment by AllanJard** [comment]
I haven't released the fix for this yet. I committed it [just last week](https://github.com/DataTables/ColReorder/commit/56e81c22b97f44eac61ae4d74ff7aec9e76e76fe). If you try the nightly build, it should be fixed there.

I must have reintroduced the error at some point - apologies.

**Comment by rttc-mm** [comment]
Thx! Sorry, I didn't realize that it was already fixed in the current sources.
