### ISSUE TITLE
BUG: Colreorder error alert when using data-order attribute on <td>

### ISSUE THREAD

**Issue by riaancillie** [DataTables/ColReorder#85]
Forum Issue: [https://datatables.net/forums/discussion/72994/bug-colreorder-error-alert-when-using-data-order-attribute-on#latest](https://datatables.net/forums/discussion/72994/bug-colreorder-error-alert-when-using-data-order-attribute-on#latest)

**Link to test case:**
[https://jsfiddle.net/riaanc/a4q7mprz/4/](https://jsfiddle.net/riaanc/a4q7mprz/4/)

**Debugger code (debug.datatables.net):**
owakel [Before error is shown]

**Error messages shown:**
```DataTables warning: table id=example - Requested unknown parameter '[object Object]' for row 2, column 4. For more information about this error, please see http://datatables.net/tn/4```

**Description of problem:**
When adding a data-order attribute on a <td> Colreorder shows an alert whenever that column is involved in re-ordering. After the alert is shown, all values in the column change to "[object Object]".

In the linked JSFiddle example, drag the Start Date column to see the behaviour. By simply removing the data-order attribute or renaming it to something else like "data123-order", the above behaviour is avoided, but then sorting by the attribute value obviously is no longer respected.

**Comment by AllanJard** [comment]
Try the nightly - that should already have this resolved: https://jsfiddle.net/fguq1by4/ .

**Comment by AllanJard** [comment]
Closing in favour of the forum discussion for this: https://datatables.net/forums/discussion/72994/bug-colreorder-error-alert-when-using-data-order-attribute-on-td#latest .
