### ISSUE TITLE
Added a cancel feature but have a minify question

### ISSUE THREAD

**Issue by reaua001** [DataTables/ColReorder#87]
In my project, I have an external box that can drag columns for table grouping and column visibility options
I needed to add a datatable.colReorder.cancel() option that cancels the re-order when dragged into that box

My question is how do I minify the edited js so that's the same way your minification is?

[Forked Files](https://github.com/reaua001/ColReorder)

**Comment by AllanJard** [comment]
This repo doesn't have the minified files and doesn't need to. However, we use Uglify are the minifier.
