### ISSUE TITLE
colReorder.enable(false) can't call internal fnDisable function

### ISSUE THREAD

**Issue by hchiam** [DataTables/ColReorder#88]
When calling `.enable(false)` I get this error: 

`Uncaught ReferenceError: fnDisable is not defined` 

![screenshot-of-production-bug](https://user-images.githubusercontent.com/18131787/179294088-df7d6e91-7b6f-437a-aa07-241f377fd0f1.png)

What I checked/tried:
* docs https://datatables.net/forums/categories/colreorder/
* forums https://datatables.net/forums/categories/colreorder/
* interactive demo of the bug: https://codepen.io/hchiam/pen/MWBjZqb?editors=1011 (open browser console, _not_ CodePen's own console, and then click the "Disable" button)

**Comment by AllanJard** [comment]
That's an embarrassing one! Thanks for letting me know about that. Fix applied and I'll add a unit test for it.

**Comment by hchiam** [comment]
Thanks for the fix @AllanJard! I found colReorder helpful for use in a production app, so this is great.
